### ISSUE TITLE
App crashes on version 2.71828

### ISSUE THREAD

**Issue by RasitAyaz** [square/picasso#2153]
Images are successfully loading in 2.5.2 version. But when I upgrade gradle to 2.71828 and update my code as: `Picasso.get().load(photoUrl).into(imgProfile);`, I am getting a runtime error;

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.leotenebris.simplemessaging, PID: 5894
    java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.runtime/javalib/core-oj.jar)
        at okhttp3.internal.Util.<clinit>(Util.java:87)
        at okhttp3.internal.Util.immutableList(Util.java:234)
        at okhttp3.OkHttpClient.<clinit>(OkHttpClient.java:124)
        at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:449)
        at com.squareup.picasso.OkHttp3Downloader.<init>(OkHttp3Downloader.java:71)
        at com.squareup.picasso.OkHttp3Downloader.<init>(OkHttp3Downloader.java:50)
        at com.squareup.picasso.OkHttp3Downloader.<init>(OkHttp3Downloader.java:40)
        at com.squareup.picasso.Picasso$Builder.build(Picasso.java:848)
        at com.squareup.picasso.Picasso.get(Picasso.java:683)
        at com.leotenebris.simplemessaging.SettingsActivity.onCreate(SettingsActivity.java:112)
        at android.app.Activity.performCreate(Activity.java:7824)
        at android.app.Activity.performCreate(Activity.java:7813)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3246)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:920)
```

**Comment by JakeWharton** [comment]
This is not a problem with Picasso but with OkHttp. You are using a version newer than 3.13 which requires Java 8 be enabled in your app. Please see https://cashapp.github.io/2019-02-05/okhttp-3-13-requires-android-5

**Comment by RasitAyaz** [comment]
> 
> 
> This is not a problem with Picasso but with OkHttp. You are using a version newer than 3.13 which requires Java 8 be enabled in your app. Please see https://cashapp.github.io/2019-02-05/okhttp-3-13-requires-android-5

Thank you, I just updated OkHttp to latest version, added compile options for compatibility and now it works fine.
