### ISSUE TITLE
picasso2.5.2  doesn't work with okhttp-2.3.0 

### ISSUE THREAD

**Issue by vagrant1991** [square/picasso#976]
04-12 21:59:55.907: E/dalvikvm(14925): Could not find class 'com.squareup.okhttp.internal.DiskLruCache$2', referenced from method com.squareup.okhttp.internal.DiskLruCache.newJournalWriter

04-12 21:59:55.897: E/dalvikvm(14925): Could not find class 'com.squareup.okhttp.internal.DiskLruCache$4', referenced from method com.squareup.okhttp.internal.DiskLruCache.<clinit>

04-12 21:59:55.937: E/AndroidRuntime(14925): FATAL EXCEPTION: main

04-12 21:59:55.937: E/AndroidRuntime(14925): java.lang.NoClassDefFoundError: com.squareup.okhttp.internal.DiskLruCache$4
04-12 21:59:55.937: E/AndroidRuntime(14925): 	at com.squareup.okhttp.internal.DiskLruCache.<clinit>(DiskLruCache.java:810)
04-12 21:59:55.937: E/AndroidRuntime(14925): 	at com.squareup.okhttp.Cache.<init>(Cache.java:168)
04-12 21:59:55.937: E/AndroidRuntime(14925): 	at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:78)
.......
......
.....
......

**Comment by JakeWharton** [comment]
This is a packaging or proguard problem with your build. Both of these versions work fine together. The fact that a class in OkHttp can't find another class in OkHttp is what indicates this.

**Comment by jhanay** [comment]
OkHttp depend on okio.jar.

**Comment by jjhesk** [comment]
Should we keep the cache module in the proguard??
